HccCoffeeMaker/src/HccCoffeeMaker/Controllers/FilterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HccCoffeeMaker.Controllers
{
    public class FilterController : Controller
    {
        public IActionResult Index(string coffeeMakerType)
        {
            ViewData["typeOfMachine"] = coffeeMakerType;
            return View();
        }

        public List<string> GetFacetsAdded(string facetsAdded)
        {
            List<string> result = new List<string>();
            string facet = "";
            for(int i = 0; i < facetsAdded.Length; i++)
            {
                if(facetsAdded[i] == ';')
                {
                    result.Add(facet);
                    facet = "";
                }
                else
                {
                    facet += facetsAdded[i];
                }
            }

            return result;
        }

        public List<string> GetFacetParameters(string facet, string facetParameters)
        {
            List<string> result = new List<string>();
            string facetName = "";
            string facetParameter = "";
            bool collectingName = true;
            for(int i = 0; i < facetParameters.Length; i++)
            {
                if(facetParameters[i] == ';')
                {
                    if(facetName == facet)
                    {
                        result.Add(facetParameter);
                    }
                    collectingName = true;
                    facetName = "";
                    facetParameter = "";
                }
                else if(facetParameters[i] == '.')
                {
                    collectingName = false;
                }
                else if(collectingName)
                {
                    facetName += facetParameters[i];
                }
                else
                {
                    facetParameter += facetParameters[i];
                }
            }

            return result;
        }

        [HttpPost]
        public IActionResult Index()
        {
            List<string> facetsAdded = GetFacetsAdded(HttpContext.Request.Form["facetsAdded"]);
            foreach(string facet in facetsAdded)
            {
                ViewData[facet] = GetFacetParameters(facet, HttpContext.Request.Form["facetParameters"]);
            }
            ViewData["facetsAdded"] = facetsAdded;
            ViewData["typeOfMachine"] = HttpContext.Request.Form["typeOfMachine"];
            return View("Index");
        }
        
    }
}

HccCoffeeMaker/src/HccCoffeeMaker/Controllers/InitialOptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HccCoffeeMaker.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HccCoffeeMaker.Models.CoffeeMakerModels;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net.Http;

namespace HccCoffeeMaker.Controllers
{
    public class InitialOptionsController : Controller
    {

        private readonly MyDatabaseContext _context;

        public InitialOptionsController(MyDatabaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            string value = HttpContext.Request.Form["firstname"];
            List<AmazonProductModel.PriceOptions> priceOptions = new List<AmazonProductModel.PriceOptions>();
            List<AmazonProductModel.ColorOptions> colorOptions = new List<AmazonProductModel.ColorOptions>();
            List<AmazonProductModel.ServingSizeOptions> servingSizeOptions = new List<AmazonProductModel.ServingSizeOptions>();
            List<AmazonProductModel.DurabilityOptions> durabilityOptions = new List<AmazonProductModel.DurabilityOptions>();
            List<AmazonProductModel.BrewingTimeOptions> brewingTimeOptions = new List<AmazonProductModel.BrewingTimeOptions>();
            List<AmazonProductModel.BrandOptions> brandOptions = new List<AmazonProductModel.BrandOptions>();
            List<AmazonProductModel.WarrantyOptions> warrantyOptions = new List<AmazonProductModel.WarrantyOptions>();
            List<AmazonProductModel.QualityOfCoffeeOptions> qualityOfCoffeeOptions = new List<AmazonProductModel.QualityOfCoffeeOptions>();

            string facetsAdded = "";
            string facetParameters = "";

            bool priceAdded = false;
            bool colorAdded = false;
            bool servingSizeAdded = false;
            bool durabilityAdded = false;
            bool brewingTimeAdded = false;
            bool brandAdded = false;
            bool warrantyAdded = false;
            bool qualityOfCoffeeAdded = false;

            foreach (var key in HttpContext.Request.Form)
            {
                foreach(var data in HttpContext.Request.Form[key.Key])
                {
                    ViewData[key.Key + "." + data] = key.Key + "." + data;
                    if (key.Key == "price")
                    {
                        if(!priceAdded)
                        {
                            facetsAdded += "price;";
                            priceAdded = true;
                        }

                        foreach (AmazonProductModel.PriceOptions priceOption in Enum.GetValues(typeof(AmazonProductModel.PriceOptions)))
                            if (priceOption.ToString() == data)
                            {
                                priceOptions.Add(priceOption);
                                facetParameters += "price." + priceOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "color")
                    {
                        if (!colorAdded)
                        {
                            facetsAdded += "color;";
                            colorAdded = true;
                        }

                        foreach (AmazonProductModel.ColorOptions colorOption in Enum.GetValues(typeof(AmazonProductModel.ColorOptions)))
                            if (colorOption.ToString() == data)
                            {
                                colorOptions.Add(colorOption);
                                facetParameters += "color." + colorOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "servingSize")
                    {
                        if (!servingSizeAdded)
                        {
                            facetsAdded += "servingSize;";
                            servingSizeAdded = true;
                        }

                        foreach (AmazonProductModel.ServingSizeOptions servingSizeOption in Enum.GetValues(typeof(AmazonProductModel.ServingSizeOptions)))
                            if (servingSizeOption.ToString() == data)
                            {
                                servingSizeOptions.Add(servingSizeOption);
                                facetParameters += "servingSize." + servingSizeOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "durability")
                    {
                        if (!durabilityAdded)
                        {
                            facetsAdded += "durability;";
                            durabilityAdded = true;
                        }

                        foreach (AmazonProductModel.DurabilityOptions durabilityOption in Enum.GetValues(typeof(AmazonProductModel.DurabilityOptions)))
                            if (durabilityOption.ToString() == data)
                            {
                                durabilityOptions.Add(durabilityOption);
                                facetParameters += "durability." + durabilityOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "brewingTime")
                    {
                        if (!brewingTimeAdded)
                        {
                            facetsAdded += "brewingTime;";
                            brewingTimeAdded = true;
                        }

                        foreach (AmazonProductModel.BrewingTimeOptions brewingTimeOption in Enum.GetValues(typeof(AmazonProductModel.BrewingTimeOptions)))
                            if (brewingTimeOption.ToString() == data)
                            {
                                brewingTimeOptions.Add(brewingTimeOption);
                                facetParameters += "brewingTime." + brewingTimeOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "brand")
                    {
                        if (!brandAdded)
                        {
                            facetsAdded += "brand;";
                            brandAdded = true;
                        }

                        foreach (AmazonProductModel.BrandOptions brandOption in Enum.GetValues(typeof(AmazonProductModel.BrandOptions)))
                            if (brandOption.ToString() == data)
                            {
                                brandOptions.Add(brandOption);
                                facetParameters += "brand." + brandOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "warranty")
                    {
                        if (!warrantyAdded)
                        {
                            facetsAdded += "warranty;";
                            warrantyAdded = true;
                        }

                        foreach (AmazonProductModel.WarrantyOptions warrantyOption in Enum.GetValues(typeof(AmazonProductModel.WarrantyOptions)))
                            if (warrantyOption.ToString() == data)
                            {
                                warrantyOptions.Add(warrantyOption);
                                facetParameters += "warranty." + warrantyOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "qualityOfCoffee")
                    {
                        if (!qualityOfCoffeeAdded)
                        {
                            facetsAdded += "qualityOfCoffee;";
                            warrantyAdded = true;
                        }

                        foreach (AmazonProductModel.QualityOfCoffeeOptions qualityOfCoffeeOption in Enum.GetValues(typeof(AmazonProductModel.QualityOfCoffeeOptions)))
                            if (qualityOfCoffeeOption.ToString() == data)
                            {
                                qualityOfCoffeeOptions.Add(qualityOfCoffeeOption);
                                facetParameters += "qualityOfCoffee." + qualityOfCoffeeOption.ToString() + ";";
                            }
                    }
                }
            }

            ViewData["facetsAdded"] = facetsAdded;
            ViewData["facetParameters"] = facetParameters;
            ViewData["typeOfMachine"] = HttpContext.Request.Form["typeOfMachine"];

            string typeOfMachine = HttpContext.Request.Form["typeOfMachine"];
            List<AmazonProductModel.TypeOfMachineOptions> typeOfMachineOptions = new List<AmazonProductModel.TypeOfMachineOptions>();
            if (typeOfMachine == "AutomaticDrip")
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.Automatic);
            else if (typeOfMachine == "SingleServePods")
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.SmallPods);
            else if (typeOfMachine == "FrenchPress")
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.FrenchPress);
            else
            {
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.Automatic);
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.SmallPods);
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.FrenchPress);
            }



            ViewData["userCurations"] = await AmazonProductModel.GetUserAddedCurations(_context);
            ViewData["products"] = await AmazonProductModel.Query(
                context: _context,
                priceOptionsInput: priceOptions,
                colorOptionsInput: colorOptions,
                servingSizeOptionsInput: servingSizeOptions,
                durabilityOptionsInput: durabilityOptions,

HccCoffeeMaker/src/HccCoffeeMaker/Views/Filter/Index.cshtml
@*Filter Options Page*@ 
@using HccCoffeeMaker.Models.CoffeeMakerModels;
@using System.Collections.Generic;

@{
    ViewData["Title"] = "Filter Page";
}

<link rel="stylesheet" type="text/css" href="~/css/Filters.css" />


<script src="~/js/jquery-1.3.2-vsdoc2.js"></script>
<script src="~/js/Filter.js"></script>




<div style="height:50px;"></div>

<div id="myDiv" class="modal"></div>




<div style="height:10px;"></div>
<div style="font-size:var(--extraLargeFont)">Select facets to filter on </div>
<div style="height:50px;"></div>

@{ var title = "";}
@{ var spaceUnderFacetSelectorTitle = "50px";}
<div style="text-align:center;width:100%;">
    @{title = "price";}
    <div id="@(title)AddedHead"></div>
    <div id="@(title)Added" class="addedFilter">
        Price <br />
        <div style="height:50px;"></div>
        <div style="font-size:var(--smallMediumFont)">
            The average price for coffee makers is $67.
        </div>
        <div class="listOptions">
            @foreach (AmazonProductModel.PriceOptions price in Enum.GetValues(typeof(AmazonProductModel.PriceOptions)))
            {
                <input type="checkbox" name="@(title)" value=@price.ToString() 
                    @( ((List<string>)ViewData["price"]) != null ? (((List<string>)ViewData["price"]).Contains(price.ToString()) ? "checked" : "" ) : "")
                /> @AmazonProductModel.OptionsString(price)<br />
            }
        </div>
        <span id="@(title)AddedSelect" class="addedFacetSelect" onclick="clickSelect(this.id)">✓</span>
        <span id="@(title)AddedClose" class="addedFacetClose" onclick="clickClose(this.id)">X</span>
    </div>
    <div class="filterElement" id="@(title)" onclick="clickFacet(this.id)" onmouseover="over(this.id)" onmouseout="out(this.id)">
        <span class="filterText">Price</span>
    </div>
    @{title = "color";}
    <div id="@(title)Added" class="addedFilter">
        Color <br />
        <div style="height:20px;"></div>
        <div style="font-size:var(--smallMediumFont)">
            While black and silver coffee makers are common, more vibrant colors are also fun.
        </div>
        <div class="listOptions">
            @foreach (AmazonProductModel.ColorOptions color in Enum.GetValues(typeof(AmazonProductModel.ColorOptions)))
            {
                <input type="checkbox" name="@(title)" value=@color.ToString() 
                    @( ((List<string>)ViewData["color"]) != null ? (((List<string>)ViewData["color"]).Contains(color.ToString()) ? "checked" : "" ) : "")       
                /> @AmazonProductModel.OptionsString(color) <br>
            }
        </div>
        <span id="@(title)AddedSelect" class="addedFacetSelect" onclick="clickSelect(this.id)">✓</span>
        <span id="@(title)AddedClose" class="addedFacetClose" onclick="clickClose(this.id)">X</span>
    </div>
    <div class="filterElement" id="@(title)" onclick="clickFacet(this.id)" onmouseover="over(this.id)" onmouseout="out(this.id)">
        <span class="filterText">Color</span>
    </div>

    @{title = "durability";}
    <div id="@(title)Added" class="addedFilter">
        Durability <br />
        <div style="height:50px;"></div>
        <div style="font-size:var(--smallMediumFont)">
            Most people are plenty satisfied with light and normal use coffee makers. 
        </div>
        <div class="listOptions">
            @foreach (AmazonProductModel.DurabilityOptions durability in Enum.GetValues(typeof(AmazonProductModel.DurabilityOptions)))
            {
                <input type="checkbox" name="@(title)" value=@durability.ToString() 
                    @( ((List<string>)ViewData["durability"]) != null ? (((List<string>)ViewData["durability"]).Contains(durability.ToString()) ? "checked" : "" ) : "")       
                /> @AmazonProductModel.OptionsString(durability) <br>
            }
        </div>
        <span id="@(title)AddedSelect" class="addedFacetSelect" onclick="clickSelect(this.id)">✓</span>
        <span id="@(title)AddedClose" class="addedFacetClose" onclick="clickClose(this.id)">X</span>
    </div>    
    <div class="filterElement" id="@(title)" onclick="clickFacet(this.id)" onmouseover="over(this.id)" onmouseout="out(this.id)">
        <span class="filterText">Durability</span>
    </div>
    @{title = "servingSize";}
    <div id="@(title)Added" class="addedFilter">
        Serving Size <br />
        <div style="height:7px;"></div>
        <div style="font-size:var(--smallMediumFont)">
            Only for yourself, or family and friends?
        </div>
        <div class="listOptions">
            @foreach (AmazonProductModel.ServingSizeOptions servingSize in Enum.GetValues(typeof(AmazonProductModel.ServingSizeOptions)))
            {
                <input type="checkbox" name="@(title)" value=@servingSize.ToString() 
                    @( ((List<string>)ViewData["servingSize"]) != null ? (((List<string>)ViewData["servingSize"]).Contains(servingSize.ToString()) ? "checked" : "" ) : "")       
                /> @AmazonProductModel.OptionsString(servingSize) <br>
            }
        </div>
        <span id="@(title)AddedSelect" class="addedFacetSelect" onclick="clickSelect(this.id)">✓</span>
        <span id="@(title)AddedClose" class="addedFacetClose" onclick="clickClose(this.id)">X</span>
    </div>
    <div class="filterElement" id="@(title)" onclick="clickFacet(this.id)" onmouseover="over(this.id)" onmouseout="out(this.id)">
        <span class="filterText">Serving Size</span>
    </div>
</div>

<div style="text-align:center;width:100%;">
    @{title = "brewingTime";}
    <div id="@(title)Added" class="addedFilter">
        Brewing Time <br />
        <div style="height:50px;"></div>
        <div style="font-size:var(--smallMediumFont)">
            A shorter brew time is useful for smaller, personal coffee machines. 
        </div>
        <div class="listOptions">
            @foreach (AmazonProductModel.BrewingTimeOptions brewingTime in Enum.GetValues(typeof(AmazonProductModel.BrewingTimeOptions)))
            {
                <input type="checkbox" name="@(title)" value=@brewingTime.ToString() 
                    @( ((List<string>)ViewData["brewingTime"]) != null ? (((List<string>)ViewData["brewingTime"]).Contains(brewingTime.ToString()) ? "checked" : "" ) : "")       
                /> @AmazonProductModel.OptionsString(brewingTime) <br>
            }
        </div>
        <span id="@(title)AddedSelect" class="addedFacetSelect" onclick="clickSelect(this.id)">✓</span>
        <span id="@(title)AddedClose" class="addedFacetClose" onclick="clickClose(this.id)">X</span>
    </div>
    <div class="filterElement" id="@(title)" onclick="clickFacet(this.id)" onmouseover="over(this.id)" onmouseout="out(this.id)">
        <span class="filterText">Brewing Time</span>
    </div>
    @{title = "brand";}
    <div id="@(title)Added" class="addedFilter">
        Brand <br />
        <div style="height:35px;"></div>
        <div style="font-size:var(--smallMediumFont)">
            Kuerig and Nespresso are newer premium brands. 
        </div>
        <div class="listOptions">
            @foreach (AmazonProductModel.BrandOptions brand in Enum.GetValues(typeof(AmazonProductModel.BrandOptions)))
            {
                <input type="checkbox" name="@(title)" value=@brand.ToString() 
                    @( ((List<string>)ViewData["brand"]) != null ? (((List<string>)ViewData["brand"]).Contains(brand.ToString()) ? "checked" : "" ) : "")       
                /> @AmazonProductModel.OptionsString(brand) <br>
            }
        </div>
        <span id="@(title)AddedSelect" class="addedFacetSelect" onclick="clickSelect(this.id)">✓</span>
        <span id="@(title)AddedClose" class="addedFacetClose" onclick="clickClose(this.id)">X</span>
    </div>
    <div class="filterElement" id="@(title)" onclick="clickFacet(this.id)" onmouseover="over(this.id)" onmouseout="out(this.id)">
        <span class="filterText">Brand</span>
    </div>

    @{title = "warranty";}
    <div id="@(title)Added" class="addedFilter">
        Warranty <br />
        <div style="height:35px;"></div>
        <div style="font-size:var(--smallMediumFont)">
            Although not a premium feature, a quality warranty can come in handy. 
        </div>
        <div class="listOptions">
            @foreach (AmazonProductModel.WarrantyOptions warranty in Enum.GetValues(typeof(AmazonProductModel.WarrantyOptions)))
            {
                <input type="checkbox" name="@(title)" value=@warranty.ToString() 
                    @( ((List<string>)ViewData["warranty"]) != null ? (((List<string>)ViewData["warranty"]).Contains(warranty.ToString()) ? "checked" : "" ) : "")       
                /> @AmazonProductModel.OptionsString(warranty) <br>
            }
        </div>
        <span id="@(title)AddedSelect" class="addedFacetSelect" onclick="clickSelect(this.id)">✓</span>
        <span id="@(title)AddedClose" class="addedFacetClose" onclick="clickClose(this.id)">X</span>
    </div>
    <div class="filterElement" id="@(title)" onclick="clickFacet(this.id)" onmouseover="over(this.id)" onmouseout="out(this.id)">
        <span class="filterText">Warranty</span>
    </div>

    @{title = "qualityOfCoffee";}
    <div id="@(title)Added" class="addedFilter">
        Quality of Coffee <br />
        <div style="height:70px;"></div>
        <div style="font-size:var(--smallMediumFont)">
            Experienced coffee enthusiast will enjoy the most premium coffee, while newcomers will enjoy all coffee. 
        </div>
        <div class="listOptions">
            @foreach (AmazonProductModel.QualityOfCoffeeOptions qualityOfCoffee in Enum.GetValues(typeof(AmazonProductModel.QualityOfCoffeeOptions)))
            {
                <input type="checkbox" name="@(title)" value=@qualityOfCoffee.ToString() 
                    @( ((List<string>)ViewData["qualityOfCoffee"]) != null ? (((List<string>)ViewData["qualityOfCoffee"]).Contains(qualityOfCoffee.ToString()) ? "checked" : "" ) : "")       
                /> @AmazonProductModel.OptionsString(qualityOfCoffee) <br>
            }
        </div>
        <span id="@(title)AddedSelect" class="addedFacetSelect" onclick="clickSelect(this.id)">✓</span>
        <span id="@(title)AddedClose" class="addedFacetClose" onclick="clickClose(this.id)">X</span>
    </div>
    <div class="filterElement" id="@(title)" onclick="clickFacet(this.id)" onmouseover="over(this.id)" onmouseout="out(this.id)">
        <span class="filterText">Quality of Coffee</span>
    </div>
</div>

@*<div style="height:200px;"></div>*@

<br />
<font style="color:var(--lightSeafoam)">.</font>
<br />
<hr />



<div style="height:50px;clear:both;"></div>
<form asp-controller="InitialOptions" asp-action="Index" method="post" style="text-align:center;" id="inputForm">
    <div id="formField" ondrop="drop(event)" ondragover="allowDrop(event)" style="text-align:center;width:100%;"></div>
    <br />
    <div style="clear:both;"></div>

    <div id="rightArrow"
         onclick="MoveToSelectionFromFilters(event, id)"
         onmouseover="MouseOverCursor(event, this.id)"
         onmouseout="MouseOutDefault(event, this.id)"
         style="display:none;">
        <font style="font-size:250px;"> > </font>
    </div>

    <input type="text" name="typeOfMachine" value="@ViewData["typeOfMachine"]" style="display:none" />
</form>


<a href="/TypeSelection/">
    <div id="leftArrow"
         onclick="Judgement(event, id)"
         onmouseover="MouseOverCursor(event, this.id)"
         onmouseout="MouseOutDefault(event, this.id)">
        <font style="font-size:250px;"> < </font>
    </div>
</a>
<div id="goBackText" style="display:block;
    position:fixed;
    left:0px;
    top:65%;
    z-index:5;
    color:var(--navyTransparent);
    width:150px;
    font-size:var(--smallMediumFont);
    text-align:center;">    
    Filters will not be retained 
</div>

    

    
<script>
    
    window.onload = function () {
        @if (ViewData["facetsAdded"] != null)
        {
            @foreach (string facet in (List<string>)ViewData["facetsAdded"])
            {
                string functionParameter = facet + "AddedSelect";
                <text>clickSelect("@functionParameter");</text>
            }
        }
    };

</script>