HccCoffeeMaker/src/HccCoffeeMaker/Controllers/FilterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HccCoffeeMaker.Controllers
{
    public class FilterController : Controller
    {
        public IActionResult Index(string coffeeMakerType)
        {
            ViewData["typeOfMachine"] = coffeeMakerType;
            return View();
        }

        public List<string> GetFacetsAdded(string facetsAdded)
        {
            List<string> result = new List<string>();
            string facet = "";
            for(int i = 0; i < facetsAdded.Length; i++)
            {
                if(facetsAdded[i] == ';')
                {
                    result.Add(facet);
                    facet = "";
                }
                else
                {
                    facet += facetsAdded[i];
                }
            }

            return result;
        }

        public List<string> GetFacetParameters(string facet, string facetParameters)
        {
            List<string> result = new List<string>();
            string facetName = "";
            string facetParameter = "";
            bool collectingName = true;
            for(int i = 0; i < facetParameters.Length; i++)
            {
                if(facetParameters[i] == ';')
                {
                    if(facetName == facet)
                    {
                        result.Add(facetParameter);
                    }
                    collectingName = true;
                    facetName = "";
                    facetParameter = "";
                }
                else if(facetParameters[i] == '.')
                {
                    collectingName = false;
                }
                else if(collectingName)
                {
                    facetName += facetParameters[i];
                }
                else
                {
                    facetParameter += facetParameters[i];
                }
            }

            return result;
        }

        [HttpPost]
        public IActionResult Index()
        {
            List<string> facetsAdded = GetFacetsAdded(HttpContext.Request.Form["facetsAdded"]);
            foreach(string facet in facetsAdded)
            {
                ViewData[facet] = GetFacetParameters(facet, HttpContext.Request.Form["facetParameters"]);
            }
            ViewData["facetsAdded"] = facetsAdded;
            ViewData["typeOfMachine"] = HttpContext.Request.Form["typeOfMachine"];
            return View("Index");
        }
        
    }
}

HccCoffeeMaker/src/HccCoffeeMaker/Controllers/InitialOptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HccCoffeeMaker.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HccCoffeeMaker.Models.CoffeeMakerModels;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net.Http;

namespace HccCoffeeMaker.Controllers
{
    public class InitialOptionsController : Controller
    {

        private readonly MyDatabaseContext _context;

        public InitialOptionsController(MyDatabaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            string value = HttpContext.Request.Form["firstname"];
            List<AmazonProductModel.PriceOptions> priceOptions = new List<AmazonProductModel.PriceOptions>();
            List<AmazonProductModel.ColorOptions> colorOptions = new List<AmazonProductModel.ColorOptions>();
            List<AmazonProductModel.ServingSizeOptions> servingSizeOptions = new List<AmazonProductModel.ServingSizeOptions>();
            List<AmazonProductModel.DurabilityOptions> durabilityOptions = new List<AmazonProductModel.DurabilityOptions>();
            List<AmazonProductModel.BrewingTimeOptions> brewingTimeOptions = new List<AmazonProductModel.BrewingTimeOptions>();
            List<AmazonProductModel.BrandOptions> brandOptions = new List<AmazonProductModel.BrandOptions>();
            List<AmazonProductModel.WarrantyOptions> warrantyOptions = new List<AmazonProductModel.WarrantyOptions>();
            List<AmazonProductModel.QualityOfCoffeeOptions> qualityOfCoffeeOptions = new List<AmazonProductModel.QualityOfCoffeeOptions>();

            string facetsAdded = "";
            string facetParameters = "";

            bool priceAdded = false;
            bool colorAdded = false;
            bool servingSizeAdded = false;
            bool durabilityAdded = false;
            bool brewingTimeAdded = false;
            bool brandAdded = false;
            bool warrantyAdded = false;
            bool qualityOfCoffeeAdded = false;

            foreach (var key in HttpContext.Request.Form)
            {
                foreach(var data in HttpContext.Request.Form[key.Key])
                {
                    ViewData[key.Key + "." + data] = key.Key + "." + data;
                    if (key.Key == "price")
                    {
                        if(!priceAdded)
                        {
                            facetsAdded += "price;";
                            priceAdded = true;
                        }

                        foreach (AmazonProductModel.PriceOptions priceOption in Enum.GetValues(typeof(AmazonProductModel.PriceOptions)))
                            if (priceOption.ToString() == data)
                            {
                                priceOptions.Add(priceOption);
                                facetParameters += "price." + priceOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "color")
                    {
                        if (!colorAdded)
                        {
                            facetsAdded += "color;";
                            colorAdded = true;
                        }

                        foreach (AmazonProductModel.ColorOptions colorOption in Enum.GetValues(typeof(AmazonProductModel.ColorOptions)))
                            if (colorOption.ToString() == data)
                            {
                                colorOptions.Add(colorOption);
                                facetParameters += "color." + colorOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "servingSize")
                    {
                        if (!servingSizeAdded)
                        {
                            facetsAdded += "servingSize;";
                            servingSizeAdded = true;
                        }

                        foreach (AmazonProductModel.ServingSizeOptions servingSizeOption in Enum.GetValues(typeof(AmazonProductModel.ServingSizeOptions)))
                            if (servingSizeOption.ToString() == data)
                            {
                                servingSizeOptions.Add(servingSizeOption);
                                facetParameters += "servingSize." + servingSizeOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "durability")
                    {
                        if (!durabilityAdded)
                        {
                            facetsAdded += "durability;";
                            durabilityAdded = true;
                        }

                        foreach (AmazonProductModel.DurabilityOptions durabilityOption in Enum.GetValues(typeof(AmazonProductModel.DurabilityOptions)))
                            if (durabilityOption.ToString() == data)
                            {
                                durabilityOptions.Add(durabilityOption);
                                facetParameters += "durability." + durabilityOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "brewingTime")
                    {
                        if (!brewingTimeAdded)
                        {
                            facetsAdded += "brewingTime;";
                            brewingTimeAdded = true;
                        }

                        foreach (AmazonProductModel.BrewingTimeOptions brewingTimeOption in Enum.GetValues(typeof(AmazonProductModel.BrewingTimeOptions)))
                            if (brewingTimeOption.ToString() == data)
                            {
                                brewingTimeOptions.Add(brewingTimeOption);
                                facetParameters += "brewingTime." + brewingTimeOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "brand")
                    {
                        if (!brandAdded)
                        {
                            facetsAdded += "brand;";
                            brandAdded = true;
                        }

                        foreach (AmazonProductModel.BrandOptions brandOption in Enum.GetValues(typeof(AmazonProductModel.BrandOptions)))
                            if (brandOption.ToString() == data)
                            {
                                brandOptions.Add(brandOption);
                                facetParameters += "brand." + brandOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "warranty")
                    {
                        if (!warrantyAdded)
                        {
                            facetsAdded += "warranty;";
                            warrantyAdded = true;
                        }

                        foreach (AmazonProductModel.WarrantyOptions warrantyOption in Enum.GetValues(typeof(AmazonProductModel.WarrantyOptions)))
                            if (warrantyOption.ToString() == data)
                            {
                                warrantyOptions.Add(warrantyOption);
                                facetParameters += "warranty." + warrantyOption.ToString() + ";";
                            }
                    }
                    else if (key.Key == "qualityOfCoffee")
                    {
                        if (!qualityOfCoffeeAdded)
                        {
                            facetsAdded += "qualityOfCoffee;";
                            warrantyAdded = true;
                        }

                        foreach (AmazonProductModel.QualityOfCoffeeOptions qualityOfCoffeeOption in Enum.GetValues(typeof(AmazonProductModel.QualityOfCoffeeOptions)))
                            if (qualityOfCoffeeOption.ToString() == data)
                            {
                                qualityOfCoffeeOptions.Add(qualityOfCoffeeOption);
                                facetParameters += "qualityOfCoffee." + qualityOfCoffeeOption.ToString() + ";";
                            }
                    }
                }
            }

            ViewData["facetsAdded"] = facetsAdded;
            ViewData["facetParameters"] = facetParameters;
            ViewData["typeOfMachine"] = HttpContext.Request.Form["typeOfMachine"];

            string typeOfMachine = HttpContext.Request.Form["typeOfMachine"];
            List<AmazonProductModel.TypeOfMachineOptions> typeOfMachineOptions = new List<AmazonProductModel.TypeOfMachineOptions>();
            if (typeOfMachine == "AutomaticDrip")
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.Automatic);
            else if (typeOfMachine == "SingleServePods")
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.SmallPods);
            else if (typeOfMachine == "FrenchPress")
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.FrenchPress);
            else
            {
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.Automatic);
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.SmallPods);
                typeOfMachineOptions.Add(AmazonProductModel.TypeOfMachineOptions.FrenchPress);
            }



            ViewData["userCurations"] = await AmazonProductModel.GetUserAddedCurations(_context);
            ViewData["products"] = await AmazonProductModel.Query(
                context: _context,
                priceOptionsInput: priceOptions,
                colorOptionsInput: colorOptions,
                servingSizeOptionsInput: servingSizeOptions,
                durabilityOptionsInput: durabilityOptions,

HccCoffeeMaker/src/HccCoffeeMaker/Views/InitialOptions/Index.cshtml
@*Index for Initial Options*@

@using HccCoffeeMaker.Models.CoffeeMakerModels;

<link rel="stylesheet" type="text/css" href="~/css/Comparison.css" />
<link rel="stylesheet" type="text/css" href="~/css/InitialOptions.css" />
<script src="~/js/InitialOptions.js" ></script>

<script>
    @*@{ 
        var a = new AmazonProductModel()
    }*@
</script>

@*<a href="javascript:history.back()">
    <div id="leftArrow"
         onclick="Judgement(event, id)"
         onmouseover="MouseOverCursor(event, this.id)"
         onmouseout="MouseOutDefault(event, this.id)" >
        <font style="font-size:250px;"> < </font>
    </div>
</a>*@

<form asp-controller="Filter" asp-action="Index" method="post" style="text-align:center;" id="inputForm">

    <div id="leftArrow"
         onclick="Judgement(event, id)"
         onmouseover="MouseOverCursor(event, this.id)"
         onmouseout="MouseOutDefault(event, this.id)"
         style="">
        <font style="font-size:250px;"> 
            < 
        </font>
    </div>

    <input type="text" name="typeOfMachine" value="@ViewData["typeOfMachine"]" style="display:none" />
    <input type="text" name="facetsAdded" value="@ViewData["facetsAdded"]" style="display:none" />
    <input type="text" name="facetParameters" value="@ViewData["facetParameters"]" style="display:none" />
</form>

<div id="goBackText" style="display:block;
    position:fixed;
    left:0px;
    top:65%;
    z-index:5;
    color:var(--navyTransparent);
    width:150px;
    font-size:var(--smallMediumFont);
    text-align:center;">
    Filters will be retained <br />Item selection will not
</div>

<div id="goBackToSelectionText" style="display:block;
    position:fixed;
    left:0px;
    top:65%;
    z-index:5;
    color:var(--navyTransparent);
    width:150px;
    font-size:var(--smallMediumFont);
    text-align:center;
    display:none">
    Item selection will match items in table
</div>


<div id="rightArrow" 
     onclick="MoveToComparison(event, id)"
     onmouseover="MouseOverCursor(event, this.id)"
     onmouseout="MouseOutDefault(event, this.id)"
     >
    <font style="font-size:250px;"> > </font>
</div>

<div id="Selection">

    <div style="height:60px;"></div>
    <div style="font-size:var(--extraLargeFont);text-align:center">Select the products you wish to compare </div>
    <hr />
    <div style="font-size:var(--largeFont);">Your curated machines </div>

    <div style="text-align:center">
        @foreach (var item in (ICollection<AmazonProductModel>)ViewData["userCurations"])
        {
            @Html.Partial("~/Views/Shared/Partials/AmazonProductPartials/AmazonProductPartialSmall.cshtml", item)
        }
    </div>
    <hr />
    <div style="font-size:var(--largeFont);">Coffee machines matching your search </div>
    <div style="text-align:center">
        @foreach (var item in (ICollection<AmazonProductModel>)ViewData["products"])
        {
            @Html.Partial("~/Views/Shared/Partials/AmazonProductPartials/AmazonProductPartialSmall.cshtml", item)
        }
    </div>


</div>

<div id="Comparison" style="display:none;">
    @Html.Partial("~/Views/InitialOptions/Comparison.cshtml");
</div>